### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by lbonillaii** [mikestephens/greti-syntax#2]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `greti-syntax` package

```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:430:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:434:35)
ThemeManager.getImportPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:438:11)
ThemeManager.refreshLessCache (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:421:75)
```

**Comment by michaelstephens** [comment]
Thanks for letting me know. I am fairly busy but I will try to get to it when I have some free time. If you want to open a PR I would be happy to merge and release.

**Comment by michaelstephens** [comment]
Fixed in version 0.5.2

**Comment by michaelstephens** [comment]
I lied, 4th time is the charm. fixed in 0.5.4

**Comment by lbonillaii** [comment]
I'll take a look, I forgot what issue I reported haha

– Luis Bonilla

**Comment by mikestephens** [comment]
I decided to be not lazy and fix it myself haha. If you update the package in atom you should be all good with no deprecation warnings.

**Comment by lbonillaii** [comment]
Ah that's right, thanks for the fix

– Luis Bonilla
