### ISSUE TITLE
Tab text overflow

### ISSUE THREAD

**Issue by iCodeForBananas** [mikestephens/greti-syntax#6]
Is this related to the theme?  Idk how to fix.

![musicbed___public_angular_modules_mbcheckout_directives_checkout_bottomhelpbar_directive_coffee___master](https://cloud.githubusercontent.com/assets/8272012/12600161/44486b60-c44c-11e5-9d43-97559c04b7e5.png)

**Comment by michaelstephens** [comment]
I have never experienced that. If anyone else confirms then I can look into it. I assume it has more to do with the theme than the syntax.
